### PR TITLE
Rewrite Version 2.0

### PR DESCRIPTION
**Pull request by Awalz**
This is a major rewrite of the project. It includes:

* Updated to Swift 4.0 and made improvements for iOS 11
* Complete overhaul of the user interface: [preview](https://i.imgur.com/go8wg2F.png)
* Refactor of the existing UI messaging to a newer, more iOS option
* Removed hamburger menu and replaced with native tab bar
* Updated launch page 
* Refactored fetching data into data manager class. View Controllers are updated with data via a global manager and notified using NotificationCenter
* Removed necessity for loading animations before view loads with cached data 
* Data is now fetched on launch
* Third party libraries are now accessed with simple API rather than individually within View Controllers

There are many more updates that went into this update. You will have to build it and check it to see them all. There are also several updates I would like to make in the coming weeks

**This pull request has conflicts and will need to be resolved (plist and launch screen storyboard).**

***Note for building***: The *NotificationBanner* library has not been updated to Swift 4.0. After updating cocoa pods, you will manually have to change the BUILD SETTINGS to use Swift 3.2 instead of Swift 4.0 for it (only for *NotificationBanner*).

### CODE REVIEW

**Comment by vrlcrypt** [comment]
@Awalz great job! Thanks for your PR! 
I merged one PR yesterday (https://github.com/ArkEcosystem/ark-ios-monitor/pull/1). 
I believe that for this reason there were conflicts with master branch in this new PR.
Can you resolve them?

**Comment by vrlcrypt** [comment]
@Awalz: Can you provide me your ARK address for bounty distribution?

**Comment by Awalz** [comment]
Yeah Ill resolve them,

Ark Address: AYdHH5TsZF796pv7gxVU1tK6DLkUxMK1VL

**Comment by Awalz** [comment]
Issues have been resolved

**Comment by Awalz** [comment]
Some weird issues with the merge. Might have to rework some settings stuff. Ill have a fix up in a little bit

**Comment by Awalz** [comment]
@vrlc92 Should be resolved. Had some problems with the `SettingsViewController` so I just ended up rewriting it. Might just need some testing with custom server settings as I don't have any to test with

**Comment by vrlcrypt** [comment]
Nice!
It looks really great!
Thanks @Awalz.

**Comment by Awalz** [comment]
@vrlc92 No worries. There is more to come!

**Comment by sleepdefic1t** [comment]
@Awalz 
Killer job on the update!!

You clearly have the hang of Swift.
But you're welcome to check out my Swift wrapper as well.
https://github.com/sleepdefic1t/ARKKit

Going hard on some IoT stuff ATM,
but send/rec-payment, voting, Delegate registration, etc is planned for the next release.

**Comment by sleepdefic1t** [comment]
@Awalz 

If you need access to Ark test servers.

Greendragon runs arknode.net
You should be able to use  api.arknode.net 

@faustbrian also just released Ark Swagger Docs that uses Arknode.net as well.
https://ark.brianfaust.me/

**Comment by Awalz** [comment]
This is good stuff, thanks.

I have plans to rewrite the model/API. ARKKit looks pretty good. Ill look into integration after I finished my new UI release with feature enhancemenets

**Comment by sleepdefic1t** [comment]
@Awalz 
Anytime.

Nice! And thank you!
Keep up the great work!!


p.s.
these may be of use down the road.
https://github.com/IBM-Swift/CommonCrypto
https://github.com/krzyzanowskim/CryptoSwift

**Pull request merged**
