### PR TITLE
2.1 Update

### PR DESCRIPTION
**Pull request by Awalz**
This is another major update to the project. The UI has been changed again and major improvements:
- Brand new UI with updated iOS theming and large Navigation bars:  [Preview](https://i.imgur.com/4B0zph6.jpg)
- Brand new dark theme: [Preview](https://i.imgur.com/VU3gCYs.jpg)
- New App Icon and launch screen
- Updated UI to support iPhone X notches and curved screen areas
- Added ability for quick switching between light and dark mode with two finger swipe on table: [Blogpost about feature](https://medium.com/@AndrewWalz/dark-mode-for-your-ios-app-bb9ab315a10f)
- Server configuration UI has been completely reworked
- Added ability for creating and store custom server presets for quick switching has been added - #4 
- Delegates, transactions, forged blocks, voters, votes, and peers now all have detail view to view for a complete information listing
- Your username is now highlighted in Delegates list
- Labels for usernames, addresses, public keys, and IDs are all copyable
- Major bug fixes

Andrew

### CODE REVIEW

**Comment by Awalz** [comment]
This update is a major change over the previous PR. While the last one was a reskin, there are several major changes to services and architecture. I have spent an extensive amount of time testing, but its worthwhile to go through it

**Comment by Awalz** [comment]
:thumbsup:

**Comment by vrlcrypt** [comment]
I will send a new version to appstore. I think it will be available next week.
Thanks for the great work.

**Comment by Awalz** [comment]
No worries!

**Pull request merged**
